all:
  children:
    dbservers:
      hosts:
        pg1:
          ansible_host: 192.168.1.201
          ansible_ssh_user: vagrant
          ansible_ssh_private_key_file: .vagrant/machines/pg1/virtualbox/private_key
        pg2:
          ansible_host: 192.168.1.202
          ansible_ssh_user: vagrant
          ansible_ssh_private_key_file: .vagrant/machines/pg2/virtualbox/private_key

  vars:
    # ##################################################
    # environment name
    # ##################################################
    env: vagrant

    # ##################################################
    # wd_hostname, `when: inventory_hostname == primary_hostname`
    # ##################################################
    primary_hostname: pg1
    standby_hostname: pg2

    # ##################################################
    # for /etc/hosts and pgpool
    # ##################################################
    backend_prefix: backend-

    vip:
      - name: pg
        ip:   192.168.1.203
        nic_dev_name: eth1

    frontend:
      - name: pg1
        ip:   192.168.1.201
      - name: pg2
        ip:   192.168.1.202

    backend:
      - name: "{{backend_prefix}}pg1"
        ip:   192.168.2.201
      - name: "{{backend_prefix}}pg2"
        ip:   192.168.2.202

    # ##################################################
    # for postgresql and pgpool
    # ##################################################
    postgres_home_dir: /var/lib/pgsql/
    archive_dir: "{{ postgres_home_dir }}{{ pg_version_major }}/archivedir/"
    backup_dir:  "{{ postgres_home_dir }}{{ pg_version_major }}/backups/"
    pgdata_dir:  "{{ postgres_home_dir }}{{ pg_version_major }}/data/"

    # database_users:
    superuser:            postgres
    superuser_password:   "{{ vault_superuser_password }}"

    recovery_user:        postgres
    recovery_password:    "{{ vault_recovery_password }}"

    pool_check_user:      pgpool
    pool_check_password:  "{{ vault_pool_check_password }}"

    replication_user:     replication
    replication_password: "{{ vault_replication_password }}"

    # ##################################################
    # for postgresql
    # ##################################################
    # max_wal_senders:                "10"
    # wal_keep_segments:              "32"
    # archive_mode:                   "off"
    # archive_command:                "cp \"%p\" \"{{ archive_dir }}%f\""
    log_filename:                   "postgresql.log"
    log_line_prefix:                "[%m]%u %d %p[%l] "
    log_min_duration_statement:     1s
    log_checkpoints:                "on"
    log_statement:                  "mod"
    log_replication_commands:       "on"
    log_autovacuum_min_duration:    "0"
    # log_connections:                "off"
    # log_disconnections:             "off"
    # max_connections:                "100"
    # superuser_reserved_connections: "3"

    pgpass:
      entries:
        - "{{ backend[0].name }}:5432:replication:{{ replication_user }}:{{ replication_password }}"
        - "{{ backend[1].name }}:5432:replication:{{ replication_user }}:{{ replication_password }}"

    pg_hba_conf:
      entries:
        - host replication {{ replication_user }} 192.168.2.0/24 md5
        - host all all 192.168.2.0/24 md5

    # ##################################################
    # for pgpool
    # ##################################################
    pcp_conf:
      entries:
        - { user: "{{ superuser       }}", pass: "{{ superuser_password  }}"}
        - { user: "{{ pool_check_user }}", pass: "{{ pool_check_password }}"}

    pool_hba_conf:
      entries:
        # - host all {{ superuser       }} 192.168.1.0/24 md5
        # - host all {{ recovery_user   }} 192.168.1.0/24 md5
        # - host all {{ pool_check_user }} 192.168.1.0/24 md5
        - host all all 0.0.0.0/0 md5
